# Generated by Django 5.2.13 on 2026-05-07 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_sharedprojectcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='architecture',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='attribution_source_creator',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='attribution_source_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='event_type',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('engagement', 'Engagement'), ('conference', 'Conference'), ('agm', 'AGM'), ('corporate_dinner', 'Corporate Dinner'), ('product_launch', 'Product Launch'), ('funeral', 'Funeral'), ('memorial', 'Memorial'), ('concert', 'Concert'), ('award_ceremony', 'Award Ceremony'), ('graduation', 'Graduation'), ('birthday', 'Birthday'), ('gala', 'Gala'), ('fundraiser', 'Fundraiser'), ('church_service', 'Church Service'), ('livestream', 'Livestream'), ('exhibition', 'Exhibition'), ('other', 'Other')], db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fork_depth',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='forked_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='projects.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('UNLISTED', 'Unlisted (link only)'), ('PUBLIC', 'Public')], db_index=True, default='PRIVATE', max_length=20),
        ),
    ]
