"""
MODULE 3 — PROJECT MANAGEMENT MODULE
======================================
Tests for the full Project CRUD lifecycle: creation, retrieval, update,
deletion, data-isolation between owners, and project sharing via UUID tokens.

Test data used
--------------
  Owner A  : planner@venuesim.com / SecurePass123!
  Owner B  : other@venuesim.com   / SecurePass123!
  Project  : "Grand Ballroom Wedding"
             room = {width:20, depth:30, height:4, wallThickness:0.15}
  Share    : UUID token generated by POST /api/projects/<id>/share/
"""

import uuid

from django.contrib.auth import get_user_model
from django.utils import timezone
from rest_framework import status

from .base import (
    ALT_EMAIL,
    ALT_PASSWORD,
    PLANNER_EMAIL,
    PLANNER_PASSWORD,
    AuthenticatedTestCase,
    create_user,
    make_project_payload,
)

User = get_user_model()

PROJECT_NAME = "Grand Ballroom Wedding"
UPDATED_NAME = "Grand Ballroom Conference"


class ProjectManagementTests(AuthenticatedTestCase):
    """TC-19 → TC-25 : Project lifecycle and data isolation."""

    MODULE = "MODULE 3 — PROJECT MANAGEMENT MODULE"

    # ── TC-19 ──────────────────────────────────────────────────────────────────

    def test_TC19_create_project_returns_201(self):
        """TC-19 | Create project with valid payload → HTTP 201 + project id"""
        payload = make_project_payload(PROJECT_NAME)
        print(f"  Input Data : name='{PROJECT_NAME}'  room={payload['room']}")
        print("  Expected   : HTTP 201 Created  ·  response contains project 'id'")

        response = self.client.post("/api/projects/", data=payload, format="json")

        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
        self.assertIn("id", response.data)
        self.assertEqual(response.data["name"], PROJECT_NAME)

    # ── TC-20 ──────────────────────────────────────────────────────────────────

    def test_TC20_retrieve_project_returns_full_data(self):
        """TC-20 | GET existing project → HTTP 200 with room, items, connections"""
        payload = make_project_payload(PROJECT_NAME)
        create_resp = self.client.post("/api/projects/", data=payload, format="json")
        self.assertEqual(create_resp.status_code, status.HTTP_201_CREATED)
        project_id = create_resp.data["id"]

        print(f"  Input Data : project_id='{project_id}'")
        print("  Expected   : HTTP 200 OK  ·  all scene fields present in response")

        response = self.client.get(f"/api/projects/{project_id}/")

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["name"], PROJECT_NAME)
        self.assertIn("room", response.data)
        self.assertIn("items", response.data)
        self.assertIn("connections", response.data)

    # ── TC-21 ──────────────────────────────────────────────────────────────────

    def test_TC21_patch_project_name_persists(self):
        """TC-21 | PATCH project name → HTTP 200 + name updated in database"""
        payload = make_project_payload(PROJECT_NAME)
        create_resp = self.client.post("/api/projects/", data=payload, format="json")
        project_id = create_resp.data["id"]

        print(f"  Input Data : project_id='{project_id}'  name='{UPDATED_NAME}'")
        print("  Expected   : HTTP 200 OK  ·  name field reflects new value")

        patch_resp = self.client.patch(
            f"/api/projects/{project_id}/",
            data={"name": UPDATED_NAME, "updatedAt": timezone.now().isoformat()},
            format="json",
        )

        self.assertEqual(patch_resp.status_code, status.HTTP_200_OK)
        self.assertEqual(patch_resp.data["name"], UPDATED_NAME)

    # ── TC-22 ──────────────────────────────────────────────────────────────────

    def test_TC22_delete_project_removes_from_list(self):
        """TC-22 | DELETE project → HTTP 204 + project absent from list"""
        payload = make_project_payload("Temporary Event")
        create_resp = self.client.post("/api/projects/", data=payload, format="json")
        project_id = create_resp.data["id"]

        print(f"  Input Data : project_id='{project_id}'")
        print("  Expected   : HTTP 204 No Content  ·  project no longer in GET /api/projects/")

        delete_resp = self.client.delete(f"/api/projects/{project_id}/")
        self.assertEqual(delete_resp.status_code, status.HTTP_204_NO_CONTENT)

        list_resp = self.client.get("/api/projects/")
        ids = [p["id"] for p in list_resp.data]
        self.assertNotIn(str(project_id), ids)

    # ── TC-23 ──────────────────────────────────────────────────────────────────

    def test_TC23_owner_isolation_hides_other_users_projects(self):
        """TC-23 | Owner B cannot see Owner A's projects via GET /api/projects/"""
        # Owner A creates a project
        payload = make_project_payload("Owner A Only")
        create_resp = self.client.post("/api/projects/", data=payload, format="json")
        project_id = create_resp.data["id"]

        print(f"  Input Data : Owner A project_id='{project_id}'  Owner B requests list")
        print("  Expected   : Owner B receives empty or different list  ·  isolation enforced")

        # Switch to Owner B
        owner_b = create_user(email=ALT_EMAIL, password=ALT_PASSWORD)
        self.client.force_authenticate(user=owner_b)

        list_resp = self.client.get("/api/projects/")
        self.assertEqual(list_resp.status_code, status.HTTP_200_OK)
        ids = [p["id"] for p in list_resp.data]
        self.assertNotIn(str(project_id), ids)

    # ── TC-24 ──────────────────────────────────────────────────────────────────

    def test_TC24_generate_share_token_returns_uuid(self):
        """TC-24 | POST /api/projects/<id>/share/ → HTTP 200 + UUID token"""
        payload = make_project_payload(PROJECT_NAME)
        create_resp = self.client.post("/api/projects/", data=payload, format="json")
        project_id = create_resp.data["id"]

        print(f"  Input Data : project_id='{project_id}'")
        print("  Expected   : HTTP 200 OK  ·  response contains 'token' (UUID string)")

        share_resp = self.client.post(f"/api/projects/{project_id}/share/")

        self.assertEqual(share_resp.status_code, status.HTTP_200_OK)
        token = share_resp.data.get("token")
        self.assertIsNotNone(token)
        # Verify it is a valid UUID
        uuid.UUID(str(token))

    # ── TC-25 ──────────────────────────────────────────────────────────────────

    def test_TC25_anonymous_access_to_shared_project(self):
        """TC-25 | Anonymous GET /api/projects/shared/<token>/ → HTTP 200"""
        payload = make_project_payload(PROJECT_NAME)
        create_resp = self.client.post("/api/projects/", data=payload, format="json")
        project_id = create_resp.data["id"]
        token = self.client.post(f"/api/projects/{project_id}/share/").data["token"]

        print(f"  Input Data : share_token='{token}'  (unauthenticated request)")
        print("  Expected   : HTTP 200 OK  ·  project data returned without auth")

        # Use a fresh unauthenticated client
        anon_client = self.client_class()
        response = anon_client.get(f"/api/projects/shared/{token}/")

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["name"], PROJECT_NAME)

    # ── TC-26 ──────────────────────────────────────────────────────────────────

    def test_TC26_nonexistent_project_returns_404(self):
        """TC-26 | GET /api/projects/<random_uuid>/ → HTTP 404"""
        random_id = uuid.uuid4()
        print(f"  Input Data : project_id='{random_id}'  (does not exist)")
        print("  Expected   : HTTP 404 Not Found")

        response = self.client.get(f"/api/projects/{random_id}/")

        self.assertEqual(response.status_code, status.HTTP_404_NOT_FOUND)
