# Generated by Django 5.2.13 on 2026-06-02 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_add_visibility_fork_architecture_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_output', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_mode', models.CharField(choices=[('single_image', 'Single Image'), ('multi_image', 'Multiple Images'), ('video', 'Walkthrough Video')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('current_stage', models.CharField(choices=[('queued', 'Queued'), ('preprocessing', 'Preprocessing'), ('object_detection', 'Object Detection'), ('segmentation', 'Segmentation'), ('depth_estimation', 'Depth Estimation'), ('room_layout', 'Room Layout'), ('sfm', 'Structure from Motion'), ('gaussian_splat', 'Gaussian Splatting'), ('scene_graph', 'Scene Graph'), ('llm_reasoning', 'LLM Reasoning'), ('asset_matching', 'Asset Matching'), ('scene_generation', 'Scene Generation'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=30)),
                ('stage_progress', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_jobs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedObject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('world_x', models.FloatField(blank=True, null=True)),
                ('world_y', models.FloatField(blank=True, null=True)),
                ('world_z', models.FloatField(blank=True, null=True)),
                ('est_width', models.FloatField(blank=True, null=True)),
                ('est_height', models.FloatField(blank=True, null=True)),
                ('est_depth', models.FloatField(blank=True, null=True)),
                ('rotation_y', models.FloatField(default=0.0)),
                ('mask_file', models.FileField(blank=True, upload_to='cv/masks/')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='venue_cv.detectionresult')),
            ],
        ),
        migrations.CreateModel(
            name='SceneGraph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('room_width', models.FloatField(default=10.0)),
                ('room_depth', models.FloatField(default=8.0)),
                ('room_height', models.FloatField(default=3.0)),
                ('venue_type', models.CharField(blank=True, max_length=60)),
                ('layout_type', models.CharField(blank=True, max_length=60)),
                ('capacity_est', models.PositiveIntegerField(blank=True, null=True)),
                ('graph_json', models.JSONField(default=dict)),
                ('llm_reasoning_json', models.JSONField(default=dict)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scene_graph', to='venue_cv.cvjob')),
            ],
        ),
        migrations.CreateModel(
            name='AssetMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=100)),
                ('asset_source', models.CharField(max_length=30)),
                ('asset_id', models.CharField(max_length=255)),
                ('asset_url', models.CharField(max_length=500)),
                ('scale_x', models.FloatField(default=1.0)),
                ('scale_y', models.FloatField(default=1.0)),
                ('scale_z', models.FloatField(default=1.0)),
                ('confidence', models.FloatField(default=1.0)),
                ('detected_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue_cv.detectedobject')),
                ('scene_graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_mappings', to='venue_cv.scenegraph')),
            ],
        ),
        migrations.CreateModel(
            name='SfMResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_poses', models.JSONField(default=list)),
                ('sparse_cloud_file', models.FileField(blank=True, upload_to='cv/sfm/sparse/')),
                ('dense_cloud_file', models.FileField(blank=True, upload_to='cv/sfm/dense/')),
                ('mesh_file', models.FileField(blank=True, upload_to='cv/sfm/mesh/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sfm', to='venue_cv.cvjob')),
            ],
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField(default=0)),
                ('original_file', models.FileField(upload_to='cv/originals/')),
                ('processed_file', models.FileField(blank=True, upload_to='cv/processed/')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('exif_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venue_cv.cvjob')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='RoomLayoutResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('walls', models.JSONField(default=list)),
                ('floor', models.JSONField(default=dict)),
                ('ceiling', models.JSONField(default=dict)),
                ('windows', models.JSONField(default=list)),
                ('doors', models.JSONField(default=list)),
                ('room_width', models.FloatField(blank=True, null=True)),
                ('room_depth', models.FloatField(blank=True, null=True)),
                ('room_height', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room_layout', to='venue_cv.venueimage')),
            ],
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detection', to='venue_cv.venueimage'),
        ),
        migrations.CreateModel(
            name='DepthResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('depth_map_file', models.FileField(upload_to='cv/depth/')),
                ('min_depth', models.FloatField(blank=True, null=True)),
                ('max_depth', models.FloatField(blank=True, null=True)),
                ('scale_factor', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='depth', to='venue_cv.venueimage')),
            ],
        ),
        migrations.CreateModel(
            name='VenueVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='cv/videos/')),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('frame_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='venue_cv.cvjob')),
            ],
        ),
        migrations.AddIndex(
            model_name='cvjob',
            index=models.Index(fields=['owner', 'status'], name='venue_cv_cv_owner_i_6e3305_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedobject',
            index=models.Index(fields=['result', 'class_name'], name='venue_cv_de_result__58d01b_idx'),
        ),
        migrations.AddIndex(
            model_name='assetmapping',
            index=models.Index(fields=['scene_graph', 'class_name'], name='venue_cv_as_scene_g_aff618_idx'),
        ),
    ]
