# Generated by Django 5.2.13 on 2026-06-02 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue_cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectedobject',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_objects', to='venue_cv.detectionresult'),
        ),
    ]
