# Generated by Django 5.2.13 on 2026-05-07 04:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0005_add_visibility_fork_architecture_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedLayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('theme', models.CharField(blank=True, max_length=100)),
                ('estimated_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('tags', models.JSONField(default=list)),
                ('cover_image_url', models.URLField(blank=True)),
                ('published_snapshot', models.JSONField(default=dict)),
                ('published_at_hash', models.CharField(blank=True, max_length=64)),
                ('moderation_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('FLAGGED', 'Flagged')], db_index=True, default='PENDING', max_length=20)),
                ('moderation_notes', models.TextField(blank=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('auto_approved', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('unique_view_count', models.PositiveIntegerField(default=0)),
                ('fork_count', models.PositiveIntegerField(default=0)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('featured_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('trending_score', models.FloatField(db_index=True, default=0.0)),
                ('trending_computed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_layouts', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_listing', to='projects.project')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='LayoutSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='LayoutVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('scene_snapshot', models.JSONField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.project')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('project', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='LayoutLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_layouts', to=settings.AUTH_USER_MODEL)),
                ('published_layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='community.publishedlayout')),
            ],
            options={
                'unique_together': {('user', 'published_layout')},
            },
        ),
    ]
